# Generated by Django 5.0.4 on 2024-05-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_requested_at_rental_created_at_rental_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='due_to',
        ),
        migrations.AddField(
            model_name='rental',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='period',
            field=models.CharField(blank=True, choices=[('matutino', 'MATUTINO'), ('vespertino', 'VESPERTINO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='period_time',
            field=models.CharField(blank=True, choices=[('matutino', 'MATUTINO'), ('vespertino', 'VESPERTINO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
