# Generated by Django 5.0.4 on 2024-05-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_rental_due_to_rental_date_rental_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='period_time',
            field=models.CharField(blank=True, choices=[('1 aula', '1 AULA'), ('2 aula', '2 AULA'), ('3 aula', '3 AULA'), ('4 aula', '4 AULA'), ('5 aula', '5 AULA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='room',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
