# Generated by Django 5.0.4 on 2024-05-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_rental_period_time_alter_rental_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='period',
            field=models.CharField(choices=[('matutino', 'MATUTINO'), ('vespertino', 'VESPERTINO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='period_time',
            field=models.CharField(choices=[('1 aula', '1 AULA'), ('2 aula', '2 AULA'), ('3 aula', '3 AULA'), ('4 aula', '4 AULA'), ('5 aula', '5 AULA')], max_length=20, null=True),
        ),
    ]
