# Generated by Django 5.0.2 on 2024-09-26 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_rental_period_time_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta')], help_text='Select the day of the week for the exclusion')),
                ('period', models.CharField(blank=True, choices=[('matutino', 'MATUTINO'), ('vespertino', 'VESPERTINO')], max_length=20, null=True)),
                ('period_time', models.CharField(blank=True, choices=[('1 aula', '1ª AULA'), ('2 aula', '2ª AULA'), ('3 aula', '3ª AULA'), ('4 aula', '4ª AULA'), ('5 aula', '5ª AULA')], max_length=20, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
    ]
